#
# Project: Wolfenstein 3-D Redux
#
# Program: wolf3dredux
#

COMPILER = gcc
CFLAGS = -Wall -c -ffast-math -funroll-loops
OLD_LDFLAGS =  -s
XLDFLAGS = -L/usr/X11R6/lib -lX11 -lXext -lXxf86dga -lXxf86vm
VORBISFLAGS = -lvorbis -lvorbisfile -logg

ODIR = Release
                                                                                
EXEBASE = wolf3dredux
EXE = $(ODIR)/$(EXEBASE)

DO_CC = $(COMPILER) $(CFLAGS) ${CPPFLAGS} -o $@ -c $<
	

PROGRAM_OBJS =  $(ODIR)/client_input.o \
		$(ODIR)/client_main.o \
		$(ODIR)/client_screen.o \
		$(ODIR)/console.o \
		$(ODIR)/keys.o \
		$(ODIR)/menu_conf.o \
		$(ODIR)/arch.o \
		$(ODIR)/cmd.o \
		$(ODIR)/common.o \
		$(ODIR)/cvar.o \
		$(ODIR)/share.o \
		$(ODIR)/ttree.o \
		$(ODIR)/cpuid.o \
		$(ODIR)/fileio.o \
		$(ODIR)/files.o \
		$(ODIR)/filestring.o \
		$(ODIR)/zippak.o \
		$(ODIR)/unix_file.o \
		$(ODIR)/glob.o \
		$(ODIR)/in_view.o \
		$(ODIR)/unix_keys.o \
		$(ODIR)/unix_mouse.o \
		$(ODIR)/unix_joystick.o \
		$(ODIR)/system.o \
		$(ODIR)/unix_system.o \
		$(ODIR)/unix_timer.o \
		$(ODIR)/font_manager.o \
		$(ODIR)/tga.o \
		$(ODIR)/wav.o \
		$(ODIR)/angle.o \
		$(ODIR)/math.o \
		$(ODIR)/matrix.o \
		$(ODIR)/random_number.o \
		$(ODIR)/vector.o \
		$(ODIR)/memory.o \
		$(ODIR)/zmem.o \
		$(ODIR)/script.o \
		$(ODIR)/sound.o \
		$(ODIR)/sound_sfx_id.o \
		$(ODIR)/sound_stream.o \
		$(ODIR)/openal_binding.o \
		$(ODIR)/openal_main.o \
		$(ODIR)/com_string.o \
		$(ODIR)/unix_main.o \
		$(ODIR)/unix_vid_sys.o \
		$(ODIR)/texture_manager.o \
		$(ODIR)/opengl_binding.o \
		$(ODIR)/opengl_draw.o \
		$(ODIR)/opengl_extension.o \
		$(ODIR)/opengl_main.o \
		$(ODIR)/opengl_texture.o \
		$(ODIR)/openglw_imp.o \
		$(ODIR)/adler32.o \
		$(ODIR)/crc32.o \
		$(ODIR)/inffast.o \
		$(ODIR)/inflate.o \
		$(ODIR)/inftrees.o \
		$(ODIR)/zutil.o \
		$(ODIR)/wolf_powerups.o \
		$(ODIR)/wolf_sprites.o \
		$(ODIR)/wolf_bj.o \
		$(ODIR)/wolf_main.o \
		$(ODIR)/wolf_client_main.o \
		$(ODIR)/wolf_sv_ccmds.o \
		$(ODIR)/wolf_common.o \
		$(ODIR)/wolf_actor_ai.o \
		$(ODIR)/wolf_actors.o \
		$(ODIR)/wolf_ai_com.o \
		$(ODIR)/wolf_player.o \
		$(ODIR)/wolf_weapon.o \
		$(ODIR)/wolf_areas.o \
		$(ODIR)/wolf_doors.o \
		$(ODIR)/wolf_level.o \
		$(ODIR)/wolf_pushwalls.o \
		$(ODIR)/wolf_math.o \
		$(ODIR)/wolf_mcredits.o \
		$(ODIR)/wolf_menu.o \
		$(ODIR)/wolf_mintermission.o \
		$(ODIR)/wolf_mintro.o \
		$(ODIR)/wolf_mnewgame.o \
		$(ODIR)/wolf_moptions.o \
		$(ODIR)/wolf_mquit.o \
		$(ODIR)/wolf_msound.o \
		$(ODIR)/wolf_mvideo.o \
		$(ODIR)/episode.o \
		$(ODIR)/wolf_raycast.o \
		$(ODIR)/wolf_renderer.o \
		$(ODIR)/wolf_opengl.o



$(EXE): $(PROGRAM_OBJS) 
	${COMPILER} -o $(EXE) $(PROGRAM_OBJS) ${LDFLAGS} $(XLDFLAGS) $(VORBISFLAGS) -lm 


#==========================================================================
#	Build
#==========================================================================

 
#
#	client/ 
#
$(ODIR)/client_input.o : client/client_input.c 
	$(DO_CC)

$(ODIR)/client_main.o : client/client_main.c 
	$(DO_CC)

$(ODIR)/client_screen.o : client/client_screen.c 
	$(DO_CC)

$(ODIR)/console.o : client/console.c 
	$(DO_CC)

$(ODIR)/keys.o : client/keys.c 
	$(DO_CC)

$(ODIR)/menu_conf.o : client/menu_conf.c 
	$(DO_CC)

#
#	common/ 
#
$(ODIR)/arch.o : common/arch.c 
	$(DO_CC)

$(ODIR)/cmd.o : common/cmd.c 
	$(DO_CC)

$(ODIR)/common.o : common/common.c 
	$(DO_CC)

$(ODIR)/cvar.o : common/cvar.c 
	$(DO_CC)

$(ODIR)/share.o : common/share.c 
	$(DO_CC)

$(ODIR)/ttree.o : common/ttree.c 
	$(DO_CC)

#
#	device/CPU/ 
#
$(ODIR)/cpuid.o : device/cpu/cpuid.c 
	$(DO_CC)

#
#	device/filesys/ 
#
$(ODIR)/fileio.o : device/filesys/fileio.c 
	$(DO_CC)

$(ODIR)/files.o : device/filesys/files.c 
	$(DO_CC)

$(ODIR)/filestring.o : device/filesys/filestring.c 
	$(DO_CC)

$(ODIR)/zippak.o : device/filesys/zippak.c 
	$(DO_CC)

$(ODIR)/unix_file.o : device/filesys/unix/unix_file.c 
	$(DO_CC)

$(ODIR)/glob.o : device/filesys/unix/glob.c
	$(DO_CC)

#
#	device/input/
#
$(ODIR)/in_view.o : device/input/in_view.c 
	$(DO_CC)

$(ODIR)/unix_keys.o : device/input/unix/unix_keys.c 
	$(DO_CC)

$(ODIR)/unix_mouse.o : device/input/unix/unix_mouse.c 
	$(DO_CC)
	
$(ODIR)/unix_joystick.o : device/input/unix/unix_joystick.c 
	$(DO_CC)

#
#	device/system/
#
$(ODIR)/system.o : device/system/system.c 
	$(DO_CC)

$(ODIR)/unix_system.o : device/system/unix/unix_system.c 
	$(DO_CC)

#
#	device/timer/
#
$(ODIR)/unix_timer.o : device/timer/unix/unix_timer.c 
	$(DO_CC)

#
#	font/
#
$(ODIR)/font_manager.o : font/font_manager.c 
	$(DO_CC)

#
#	loaders/
#
$(ODIR)/tga.o : loaders/tga.c 
	$(DO_CC)

$(ODIR)/wav.o : loaders/wav.c 
	$(DO_CC)

#
#	math/
#
$(ODIR)/angle.o : math/angle.c 
	$(DO_CC)

$(ODIR)/math.o : math/math.c 
	$(DO_CC)

$(ODIR)/matrix.o : math/matrix.c 
	$(DO_CC)

$(ODIR)/random_number.o : math/random_number.c 
	$(DO_CC)

$(ODIR)/vector.o : math/vector.c 
	$(DO_CC)


#
#	memory/
#
$(ODIR)/memory.o : memory/memory.c 
	$(DO_CC)

$(ODIR)/zmem.o : memory/zmem.c 
	$(DO_CC)

#
#	script/
#
$(ODIR)/script.o : script/script.c 
	$(DO_CC)

#
#	sound/
#
$(ODIR)/sound.o : sound/sound.c 
	$(DO_CC)

$(ODIR)/sound_sfx_id.o : sound/sound_sfx_id.c 
	$(DO_CC)

$(ODIR)/sound_stream.o : sound/sound_stream.c 
	$(DO_CC)

$(ODIR)/openal_binding.o : sound/openal/openal_binding.c 
	$(DO_CC)

$(ODIR)/openal_main.o : sound/openal/openal_main.c 
	$(DO_CC)

#
#	string/
#
$(ODIR)/com_string.o : string/com_string.c 
	$(DO_CC)


#
#	unix/
#
$(ODIR)/unix_main.o : unix/unix_main.c 
	$(DO_CC)

$(ODIR)/unix_vid_sys.o : unix/unix_vid_sys.c 
	$(DO_CC)

	
#
#	video/
#
$(ODIR)/texture_manager.o : video/texture_manager.c 
	$(DO_CC)


#
#	video/opengl/
#
$(ODIR)/opengl_binding.o : video/opengl/opengl_binding.c
	$(DO_CC)

$(ODIR)/opengl_draw.o : video/opengl/opengl_draw.c 
	$(DO_CC)

$(ODIR)/opengl_extension.o : video/opengl/opengl_extension.c 
	$(DO_CC)

$(ODIR)/opengl_main.o : video/opengl/opengl_main.c 
	$(DO_CC)

$(ODIR)/opengl_texture.o : video/opengl/opengl_texture.c 
	$(DO_CC)

$(ODIR)/opengl_interface.o : video/opengl/unix/opengl_interface.c 
	$(DO_CC)


#
#	video/opengl/unix/
#
$(ODIR)/openglw_imp.o : video/opengl/unix/openglw_imp.c 
	$(DO_CC)

#
#	zlib/
#
$(ODIR)/adler32.o : zlib/adler32.c 
	$(DO_CC)

$(ODIR)/crc32.o : zlib/crc32.c 
	$(DO_CC)

$(ODIR)/inffast.o : zlib/inffast.c 
	$(DO_CC)

$(ODIR)/inflate.o : zlib/inflate.c 
	$(DO_CC)

$(ODIR)/inftrees.o : zlib/inftrees.c 
	$(DO_CC)

$(ODIR)/zutil.o : zlib/zutil.c 
	$(DO_CC)

##
##	game/wolf3d/
##
$(ODIR)/wolf_main.o : game/wolf3d/wolf_main.c 
	$(DO_CC)

#
#	game/wolf3d/client/
#
$(ODIR)/wolf_client_main.o : game/wolf3d/client/wolf_client_main.c 
	$(DO_CC)

$(ODIR)/wolf_sv_ccmds.o : game/wolf3d/client/wolf_sv_ccmds.c 
	$(DO_CC)

#
#	game/wolf3d/common/
#
$(ODIR)/wolf_common.o : game/wolf3d/common/wolf_common.c 
	$(DO_CC)

#
#	game/wolf3d/entities/
#
$(ODIR)/wolf_actor_ai.o : game/wolf3d/entities/wolf_actor_ai.c 
	$(DO_CC)

$(ODIR)/wolf_actors.o : game/wolf3d/entities/wolf_actors.c 
	$(DO_CC)

$(ODIR)/wolf_ai_com.o : game/wolf3d/entities/wolf_ai_com.c 
	$(DO_CC)

$(ODIR)/wolf_bj.o : game/wolf3d/entities/wolf_bj.c 
	$(DO_CC)

$(ODIR)/wolf_player.o : game/wolf3d/entities/wolf_player.c 
	$(DO_CC)

$(ODIR)/wolf_powerups.o : game/wolf3d/entities/wolf_powerups.c 
	$(DO_CC)

$(ODIR)/wolf_sprites.o : game/wolf3d/entities/wolf_sprites.c 
	$(DO_CC)

$(ODIR)/wolf_weapon.o : game/wolf3d/entities/wolf_weapon.c 
	$(DO_CC)



#
#	game/wolf3d/level/
#
$(ODIR)/wolf_areas.o : game/wolf3d/level/wolf_areas.c 
	$(DO_CC)

$(ODIR)/wolf_doors.o : game/wolf3d/level/wolf_doors.c 
	$(DO_CC)

$(ODIR)/wolf_level.o : game/wolf3d/level/wolf_level.c 
	$(DO_CC)

$(ODIR)/wolf_pushwalls.o : game/wolf3d/level/wolf_pushwalls.c 
	$(DO_CC)

#
#	game/wolf3d/math/
#
$(ODIR)/wolf_math.o : game/wolf3d/math/wolf_math.c 
	$(DO_CC)

#
#	game/wolf3d/menu/
#
$(ODIR)/wolf_mcredits.o : game/wolf3d/menu/wolf_mcredits.c 
	$(DO_CC)

$(ODIR)/wolf_menu.o : game/wolf3d/menu/wolf_menu.c 
	$(DO_CC)

$(ODIR)/wolf_mintermission.o : game/wolf3d/menu/wolf_mintermission.c 
	$(DO_CC)

$(ODIR)/wolf_mintro.o : game/wolf3d/menu/wolf_mintro.c 
	$(DO_CC)

$(ODIR)/wolf_mnewgame.o : game/wolf3d/menu/wolf_mnewgame.c 
	$(DO_CC)

$(ODIR)/wolf_moptions.o : game/wolf3d/menu/wolf_moptions.c 
	$(DO_CC)

$(ODIR)/wolf_mquit.o : game/wolf3d/menu/wolf_mquit.c 
	$(DO_CC)

$(ODIR)/wolf_msound.o : game/wolf3d/menu/wolf_msound.c 
	$(DO_CC)

$(ODIR)/wolf_mvideo.o : game/wolf3d/menu/wolf_mvideo.c 
	$(DO_CC)

#
#	game/wolf3d/script/
#
$(ODIR)/episode.o : game/wolf3d/script/episode.c
	$(DO_CC)

#
#	game/wolf3d/video/
#
$(ODIR)/wolf_raycast.o : game/wolf3d/video/wolf_raycast.c 
	$(DO_CC)

$(ODIR)/wolf_renderer.o : game/wolf3d/video/wolf_renderer.c 
	$(DO_CC)

#
#	game/wolf3d/video/opengl/
#
$(ODIR)/wolf_opengl.o : game/wolf3d/video/opengl/wolf_opengl.c 
	$(DO_CC)






#==========================================================================
#	Misc
#==========================================================================
clean:
	rm -f $(ODIR)/*.o $(EXE)
.PHONY: clean
