name: cooljeanius/Wolfenstein3DFromSource
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -q install libvorbis-dev libvorbis0a libvorbisenc2 libvorbisfile3 libxxf86dga-dev libxxf86dga1 libxxf86dga1-dbg x11proto-xf86dga-dev libgbm-dev libgbm1 libgl1-mesa-dev libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgles2-mesa libgles2-mesa-dev libosmesa6 libosmesa6-dev libxatracker-dev mesa-common-dev libxxf86vm-dev libxxf86vm1 libxxf86vm1-dbg libdmalloc-dev libdmalloc5 libglu1-mesa libglu1-mesa-dev gdb nocache bmake gdb-doc gdbserver ${{ matrix.compiler }}
    - name: Build
      run: |
        cd wolf3dredux_0.01
        ./configure --with-x --enable-silent-rules CC="${{ matrix.compiler }}"
        make
        make -f makefile_orig || bmake makefile.freebsd
        make check
        make analyze || make ms-compat || make -C gnulib_replacement_funcs check
    - name: Debug failures
      if: failure()
      run: |
        if test -x "$(which locate)" && locate --version >/dev/null 2>/dev/null; then \
          echo "locating <GL/glu.h>..."; \
          locate "GL/glu.h" || echo "locating <GL/glu.h> failed!"; \
          if test -r config.log; then cat config.log; \
          elif test -r wolf3dredux_0.01/config.log; then \
            stat wolf3dredux_0.01/config.log && cat wolf3dredux_0.01/config.log; \
          fi; \
        elif test -x "$(which mlocate)"; then \
          echo "mlocate-ing <GL/glu.h>..."; \
          mlocate "GL/glu.h" || echo "mlocate-ing <GL/glu.h> failed!"; \
        elif test -x "$(which find)" && test -r / && test -d /usr/include; then \
          echo "finding <GL/glu.h>..."; \
          find / -name "GL/glu.h" -print 2>/dev/null || echo "finding <GL/glu.h> failed!"; \
        else ls -AR; fi; sleep 1
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - clang
        - gcc
